---
  - name: My Playbook
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io
      apt:
        name: docker.io
        state: present
        force_apt_get: yes
        update_cache: yes

    - name: Install Python3
      apt:
        name: python3-pip
        state: present
        force_apt_get: yes

    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Install docker container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        published_ports: 80:80
        state: started
        restart_policy: always

    - name: Start Docker on VM start
      systemd:
        name: docker
        enabled: yes
